### ISSUE TITLE
Upgrade elasticmq to version 1.5.4

### ISSUE THREAD

**Issue by C4n4rd0** [YOU54F/serverless-offline-plugins#2]
Is it possible to create a new version of the serverless offline elasticmq plugin with an upgrade of elasticmq to get thé last features?

**Comment by C4n4rd0** [comment]
I've created this repo from your code: https://www.npmjs.com/package/serverless-offline-elasticmq-localhost
If you want to merge both, just let me know.

**Comment by YOU54F** [comment]
Yeh @C4n4rd0, yeah feel free to make a pull request, I would be happy to merge it. Makes sense to allow the user to self-define a version themselves 👍🏾

**Comment by C4n4rd0** [comment]
Here it is: [https://github.com/YOU54F/serverless-offline-plugins/pull/3](url)
And sorry for answering so lately.

**Comment by YOU54F** [comment]
nice one and no worries at all!

**Comment by YOU54F** [comment]
now released as 0.0.12 - thanks @C4n4rd0

**Comment by C4n4rd0** [comment]
Thank you for your plugin. It helped me a lot. It was the least I could do.
